BOCHS				?= bochs
BOCHS_DEBUG			?= $(BOCHS)
ENV_SUBSTITUTE		?= envsubst

BOCHS_CONFIG_TEMPLATE	:= $(BUILDSYSTEM_ROOT)$(PATH_SEPARATOR)Configuration Scripts$(PATH_SEPARATOR)Bochs.bochsrc.in
BOCHS_CONFIG			:= $(EMULATOR_WORK_ROOT)$(PATH_SEPARATOR)Bochs.bochsrc
BOCHS_RUN_COMMANDS		:= $(BUILDSYSTEM_ROOT)$(PATH_SEPARATOR)Configuration Scripts$(PATH_SEPARATOR)Bochs Run.rc

eBOCHS_CONFIG_TEMPLATE	:= $(call escape_path,$(BOCHS_CONFIG_TEMPLATE))
eBOCHS_CONFIG			:= $(call escape_path,$(BOCHS_CONFIG))

BOCHS_CPU			?= pentium
BOCHS_MEMORY		?= 8
BOCHS_HDD_CYLINDERS	?= 130
BOCHS_HDD_HEADS		?= 16
BOCHS_HDD_SECTORS	?= 63

BOCHS_ENVIRONMENT = \
	CORE_BOCHS_CPU="$(BOCHS_CPU)" \
	CORE_BOCHS_MEMORY="$(BOCHS_MEMORY)" \
	CORE_BOCHS_HDD_IMAGE="$(EMULATOR_HDD_IMAGE)" \
	CORE_BOCHS_HDD_CYLINDERS="$(BOCHS_HDD_CYLINDERS)" \
	CORE_BOCHS_HDD_HEADS="$(BOCHS_HDD_HEADS)" \
	CORE_BOCHS_HDD_SECTORS="$(BOCHS_HDD_SECTORS)" \
	CORE_BOCHS_FLOPPY_IMAGE="$(FLOPPY_IMG)"

.PHONY: bochs bochs-debug FORCE_BOCHS_CONFIG

$(eBOCHS_CONFIG): $(eBOCHS_CONFIG_TEMPLATE) FORCE_BOCHS_CONFIG
	@$(CMD_MKDIR_P) "$(EMULATOR_WORK_ROOT)"
	@$(BOCHS_ENVIRONMENT) $(ENV_SUBSTITUTE) < "$<" > "$@"

FORCE_BOCHS_CONFIG:

bochs: $(eFLOPPY_IMG) $(eEMULATOR_HDD_IMAGE) $(eBOCHS_CONFIG)
	@$(BOCHS) -unlock -f "$(BOCHS_CONFIG)" -q -rc "$(BOCHS_RUN_COMMANDS)"

bochs-debug: $(eFLOPPY_IMG) $(eEMULATOR_HDD_IMAGE) $(eBOCHS_CONFIG)
	@$(BOCHS_DEBUG) -unlock -f "$(BOCHS_CONFIG)" -q
