FASMG_ROOT				:= $(THIRDPARTY_ROOT)$(PATH_SEPARATOR)fasmg$(PATH_SEPARATOR)core
FASMG_X86_INCLUDE_ROOT	:= $(FASMG_ROOT)$(PATH_SEPARATOR)examples$(PATH_SEPARATOR)x86$(PATH_SEPARATOR)include
FASMG_UTILITY_ROOT		:= $(THIRDPARTY_ROOT)$(PATH_SEPARATOR)fasmg$(PATH_SEPARATOR)packages$(PATH_SEPARATOR)utility
ASSEMBLY_ROOT			:= $(ABS_ROOT)$(PATH_SEPARATOR)Assembly
ASSEMBLY_PRELUDE		:= $(ASSEMBLY_ROOT)$(PATH_SEPARATOR)Prelude.asm
FASMG_LISTING_INCLUDE	:= $(FASMG_UTILITY_ROOT)$(PATH_SEPARATOR)listing2.inc

eFASMG_PRELUDE_SOURCES := \
	$(call escape_path,$(ASSEMBLY_PRELUDE)) \
	$(call escape_path,$(FASMG_LISTING_INCLUDE)) \
	$(call escape_path,$(FASMG_UTILITY_ROOT)$(PATH_SEPARATOR)xcalm.inc)

ifeq ($(HOST),Core5)
    FASMG	:= $(FASMG_ROOT)$(PATH_SEPARATOR)Flat-Assembler-g.bin
else
    FASMG	:= $(FASMG_ROOT)$(PATH_SEPARATOR)fasmg
endif

eFASMG		:= $(call encode_path,$(FASMG))
CMD_FASMG	= "$(call decode_path,$(eFASMG))" -n \
	-i "include '$(FASMG_X86_INCLUDE_ROOT)$(PATH_SEPARATOR)p5.inc'" \
	-i "include '$(FASMG_LISTING_INCLUDE)'" \
	-i "include '$(ASSEMBLY_PRELUDE)'" \
	$(3) "$(1)" "$(2)"

export FASMG_ROOT FASMG_X86_INCLUDE_ROOT FASMG_UTILITY_ROOT FASMG
export ASSEMBLY_ROOT ASSEMBLY_PRELUDE
export eFASMG_PRELUDE_SOURCES
export CMD_FASMG
