
HOST_TOOLS_WORK_ROOT	:= $(WORK_ROOT)$(PATH_SEPARATOR)Host Tools$(PATH_SEPARATOR)$(HOST)

INSTALL_FAT_BOOT_FILE_ROOT		:= $(TOOLS_ROOT)$(PATH_SEPARATOR)Install FAT Boot File
INSTALL_FAT_BOOT_FILE_SOURCE	:= $(INSTALL_FAT_BOOT_FILE_ROOT)$(PATH_SEPARATOR)Source$(PATH_SEPARATOR)Main.asm
INSTALL_FAT_BOOT_FILE			:= $(HOST_TOOLS_WORK_ROOT)$(PATH_SEPARATOR)Install FAT Boot File

eINSTALL_FAT_BOOT_FILE_SOURCE	:= $(call escape_path,$(INSTALL_FAT_BOOT_FILE_SOURCE))
eINSTALL_FAT_BOOT_FILE_SOURCES	:= $(eINSTALL_FAT_BOOT_FILE_SOURCE) $(eFASMG_PRELUDE_SOURCES) \
	$(call escape_path,$(INSTALL_FAT_BOOT_FILE_ROOT)$(PATH_SEPARATOR)Source$(PATH_SEPARATOR)Arguments.asm) \
	$(call escape_path,$(INSTALL_FAT_BOOT_FILE_ROOT)$(PATH_SEPARATOR)Source$(PATH_SEPARATOR)FAT12.asm) \
	$(call escape_path,$(INSTALL_FAT_BOOT_FILE_ROOT)$(PATH_SEPARATOR)Source$(PATH_SEPARATOR)String.asm) \
	$(call escape_path,$(INSTALL_FAT_BOOT_FILE_ROOT)$(PATH_SEPARATOR)Source$(PATH_SEPARATOR)Platform$(PATH_SEPARATOR)$(HOST).asm)
eINSTALL_FAT_BOOT_FILE			:= $(call escape_path,$(INSTALL_FAT_BOOT_FILE))

ifeq ($(HOST),Core5)
    INSTALL_FAT_BOOT_FILE_DEFINES := -i "define HOST_CORE5 1"
else
    INSTALL_FAT_BOOT_FILE_DEFINES := -i "define HOST_LINUX 1" -i "define ELFEXE_INCLUDE '$(FASMG_X86_INCLUDE_ROOT)$(PATH_SEPARATOR)format$(PATH_SEPARATOR)elfexe.inc'"
endif

$(eINSTALL_FAT_BOOT_FILE): $(eINSTALL_FAT_BOOT_FILE_SOURCES)
	@$(CMD_MKDIR_P) "$(HOST_TOOLS_WORK_ROOT)"
	@$(call CMD_FASMG,$<,$@,$(INSTALL_FAT_BOOT_FILE_DEFINES))
ifeq ($(HOST),Linux)
	@chmod +x "$@"
endif

CMD_INSTALL_FAT_BOOT_FILE = \
        "$(INSTALL_FAT_BOOT_FILE)" \
            -Image "$(1)" \
            -Source "$(2)"

.PHONY: host-tools

host-tools: $(eINSTALL_FAT_BOOT_FILE)

export HOST_TOOLS_WORK_ROOT

export INSTALL_FAT_BOOT_FILE CMD_INSTALL_FAT_BOOT_FILE
