BOOTLOADER_ROOT				:= $(ABS_ROOT)$(PATH_SEPARATOR)Boot Loader
BOOTLOADER_STAGE1_SOURCE	:= $(BOOTLOADER_ROOT)$(PATH_SEPARATOR)Boot Sector.asm
BOOTLOADER_STAGE2_ROOT		:= $(BOOTLOADER_ROOT)$(PATH_SEPARATOR)Stage 2 Source
BOOTLOADER_STAGE2_SOURCE	:= $(BOOTLOADER_STAGE2_ROOT)$(PATH_SEPARATOR)Main.asm

BOOTLOADER_OUTPUT_ROOT		:= $(WORK_ROOT)$(PATH_SEPARATOR)Boot Loader
BOOTLOADER_STAGE1			:= $(BOOTLOADER_OUTPUT_ROOT)$(PATH_SEPARATOR)Boot Sector
BOOTLOADER_STAGE2			:= $(BOOTLOADER_OUTPUT_ROOT)$(PATH_SEPARATOR)Core5 Boot Loader

eBOOTLOADER_STAGE1_SOURCE	:= $(call escape_path,$(BOOTLOADER_STAGE1_SOURCE))
eBOOTLOADER_STAGE2_SOURCE	:= $(call escape_path,$(BOOTLOADER_STAGE2_SOURCE))
eBOOTLOADER_STAGE1			:= $(call escape_path,$(BOOTLOADER_STAGE1))
eBOOTLOADER_STAGE2			:= $(call escape_path,$(BOOTLOADER_STAGE2))

ifeq ($(HOST),Linux)
	OBJCOPY ?= objcopy
	GDB_SYMBOL_BUILDER := $(BUILDSYSTEM_ROOT)$(PATH_SEPARATOR)Configuration Scripts$(PATH_SEPARATOR)Make GDB Symbols.sh
	BOOTLOADER_STAGE1_SYMBOLS := $(BOOTLOADER_STAGE1).sym
	BOOTLOADER_STAGE2_SYMBOLS := $(BOOTLOADER_STAGE2).sym
	eGDB_SYMBOL_BUILDER := $(call escape_path,$(GDB_SYMBOL_BUILDER))
	eBOOTLOADER_STAGE1_SYMBOLS := $(call escape_path,$(BOOTLOADER_STAGE1_SYMBOLS))
	eBOOTLOADER_STAGE2_SYMBOLS := $(call escape_path,$(BOOTLOADER_STAGE2_SYMBOLS))
endif

eBOOTLOADER_STAGE2_SOURCES := $(eBOOTLOADER_STAGE2_SOURCE)

$(eBOOTLOADER_STAGE1): $(eBOOTLOADER_STAGE1_SOURCE) $(eBOOTLOADER_STAGE2) $(eFASMG_PRELUDE_SOURCES)
	@$(CMD_MKDIR_P) "$(BOOTLOADER_OUTPUT_ROOT)"
	@$(call CMD_FASMG,$<,$@,-i "define Stage2Path '$(BOOTLOADER_STAGE2)'")

$(eBOOTLOADER_STAGE2): $(eBOOTLOADER_STAGE2_SOURCES) $(eFASMG_PRELUDE_SOURCES)
	@$(CMD_MKDIR_P) "$(BOOTLOADER_OUTPUT_ROOT)"
	@$(call CMD_FASMG,$<,$@)

ifeq ($(HOST),Linux)
$(eBOOTLOADER_STAGE1_SYMBOLS): $(eBOOTLOADER_STAGE1) $(eGDB_SYMBOL_BUILDER)
	@"$(GDB_SYMBOL_BUILDER)" "$(OBJCOPY)" "$<" "$<.lst" "$@" 0x7C00

$(eBOOTLOADER_STAGE2_SYMBOLS): $(eBOOTLOADER_STAGE2) $(eGDB_SYMBOL_BUILDER)
	@"$(GDB_SYMBOL_BUILDER)" "$(OBJCOPY)" "$<" "$<.lst" "$@" 0

bootloader: $(eBOOTLOADER_STAGE1_SYMBOLS) $(eBOOTLOADER_STAGE2_SYMBOLS)
endif

export BOOTLOADER_ROOT BOOTLOADER_STAGE2_ROOT
export BOOTLOADER_STAGE1 BOOTLOADER_STAGE2
export BOOTLOADER_STAGE1_SYMBOLS BOOTLOADER_STAGE2_SYMBOLS
